### ISSUE TITLE
LatexCloud API and API doucmentation. 

### ISSUE THREAD

**Issue by moisestohias** [cloudlatex-team/cloudlatex-cli-plugin#23]
Hi, is there an API and API documentation for CloudLatex, for someone to create a Sublime plugin, which uses Python.

**Comment by moritanian** [comment]
There is no API documentation now. 
Please refer to the typescript implementation in this repository.

https://github.com/cloudlatex-team/cloudlatex-cli-plugin/blob/main/src/backend/cloudlatex/webAppApi.ts
