### ISSUE TITLE
プロジェクト作成後に`.`から始まるファイルを作成できるようにして欲しい

### ISSUE THREAD

**Issue by xryuseix** [cloudlatex-team/cloudlatex-cli-plugin#27]
## 問題内容

現在WebサービスのCloud LaTeXは`.`で始まる名前のファイルを作成できません．
![スクリーンショット 2023-01-10 17 01 49](https://user-images.githubusercontent.com/51394682/211494487-6c6054f8-91df-4913-b326-c938a74d19f5.png)

私は[VSCode拡張機能](https://github.com/cloudlatex-team/cloudlatex-vscode-extension)で本プラグインを使用するに当たって，`.textlintrc`や`.gitignore`などいくつかの`.`から始まるファイルを作成したいと考えています．しかし，これらのファイルを作成すると以下のエラーメッセージが出力され，今後ファイル同期ができなくなってしまいます．

以下，`.`から始まるファイルを作成した時の本プラグインのログです．

```
[Error - 04:57:03] Error in synchronizing files: upload : '.textlintrc' :  : Error: {"size":0,"timeout":0}
    at CLWebAppApi.<anonymous> (/Users/foobar/.vscode/extensions/cloudlatex.cloudlatex-2.0.0/node_modules/cloudlatex-cli-plugin/dist/src/backend/cloudlatex/webAppApi.js:158:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/foobar/.vscode/extensions/cloudlatex.cloudlatex-2.0.0/node_modules/cloudlatex-cli-plugin/dist/src/backend/cloudlatex/webAppApi.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

## 期待される結果

`.`で始まる名前のファイルを作成しても，[fileWatcher](https://github.com/cloudlatex-team/cloudlatex-cli-plugin/blob/05f3c8fc3715ac58e3adf20c92f7774981d62b34/src/fileService/fileWatcher.ts)で捕捉されない/または同期されないようにしていただきたいです．

## 対応策

いずれかの方法で対応していただくことが可能です．

### 1. `watcherOption.ignored`を設定する

現在TODOとしていくつかファイルがignoredに設定されていますが，`/\..*/`を追加していただくことで全ての`.`で始まる名前のファイルを無視可能であると考えられます．

https://github.com/cloudlatex-team/cloudlatex-cli-plugin/blob/05f3c8fc3715ac58e3adf20c92f7774981d62b34/src/fileService/fileWatcher.ts#L23

### 2. ファイルの同期をスキップする

`watcherOption.ignored`に設定されたファイルを「同期してもエラーは発生しないが，同期すべきではないファイル一覧」とするならば，以下の箇所において`.`で始まる名前のファイルをスキップするようにコードを変更する方が適切であると考えられます．

https://github.com/cloudlatex-team/cloudlatex-cli-plugin/blob/05f3c8fc3715ac58e3adf20c92f7774981d62b34/src/fileService/syncManager.ts#L210-L216

```ts
if (path.basename(file.relativePath)?.[0] !== '.') {
  const task = this.syncWithLocalTask(file);
  tasks.push(task);
  this.logger.log(`Push: ${file.relativePath} ${task.name}`);

  if (!file.isFolder) {
    this.fileChanged = true;
  }
} else {
  this.logger.log(`Skip: ${file.relativePath}`);
}
```

### 3.`watcherOption.ignored`を[VSCode拡張機能](https://github.com/cloudlatex-team/cloudlatex-vscode-extension)のプロジェクト設定で設定できるようにする

現在プロジェクト内でnode_modulesなどの大きなファイルを生成するとパフォーマンスが落ちてしまいます．そのため，いずれ同期しないファイルに関してはユーザが定義できると非常にありがたいです．

長文失礼いたしました．ご検討よろしくお願いいたします．

**Comment by moritanian** [comment]
https://github.com/cloudlatex-team/cloudlatex-vscode-extension/issues/25
こちらの議論の通り、vscodeのプロジェクト設定から同期するファイルを制御できるようにする予定です。

**Comment by xryuseix** [comment]
ご検討ありがとうございます．こちらのissueはcloseさせていただきます．よろしくお願いいたします．
